### ISSUE TITLE
vlcradio installation scripty fails on Rasbian Buster

### ISSUE THREAD

**Issue by bobrathbone** [pimoroni/phat-beat#28]
Running "curl https://get.pimoroni.com/vlcradio | bash" gives the following error:
------------------------------------------------
The VLC Radio installer
does not work on this version of Raspbian.
Check https://github.com//
for additional information and support
------------------------------------------------

This is because there is no check for Buster in the 
Pimoroni/phatbeat/projects/vlc-radio/setup.sh installation script
The raspbian_check() routine needs to be modified as shown below to support Rasbian Buster
 
 -----------------------------------------------------------------
raspbian_check() {
    IS_SUPPORTED=false
    IS_EXPERIMENTAL=false

    if [ -f /etc/os-release ]; then
        if cat /etc/os-release | grep -q "/sid"; then
            IS_SUPPORTED=false && IS_EXPERIMENTAL=true
        elif cat /etc/os-release | grep -q "stretch"; then
            IS_SUPPORTED=false && IS_EXPERIMENTAL=true
        elif cat /etc/os-release | grep -q "jessie"; then
            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
        elif cat /etc/os-release | grep -q "wheezy"; then
            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
         elif cat /etc/os-release | grep -q "buster"; then
            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
        else
            IS_SUPPORTED=false && IS_EXPERIMENTAL=false
        fi
    fi
}

I have tested it with the above modification and vlc-radio then installs and runs fine.
Bob Rathbone

**Comment by Gadgetoid** [comment]
This was kindly fixed by a contributor in https://github.com/pimoroni/phat-beat/pull/26 while it totally flew me by. Thanks for bringing it up!

**Comment by bobrathbone** [comment]
I am still getting the same failure after a fresh install. Please see 
[(https://github.com/pimoroni/phat-beat/pull/26)]
